name: Database Schema Check

on:
  push:
    paths:
      - 'prisma/schema.prisma'
  pull_request:
    paths:
      - 'prisma/schema.prisma'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Validate Schema
        run: pnpm prisma validate
        
      - name: Check Database Compatibility
        run: |
          pnpm prisma generate
          pnpm prisma db pull --force
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
      - name: Check Pending Migrations
        run: |
          pnpm prisma migrate diff \
            --from-url ${{ secrets.DATABASE_URL }} \
            --to-schema-datamodel prisma/schema.prisma \
            --exit-code 